### ISSUE TITLE
"Class 'rex_global_settings' not found"

### ISSUE THREAD

**Issue by skerbis** [phoebusryan/rex_address#11]
Release 2.0.1 - boot.php -
Beim Update:
![bildschirmfoto 2018-02-16 um 11 00 38](https://user-images.githubusercontent.com/791247/36302426-b8955d2c-1308-11e8-9dcb-cbee4a6a19e0.png)

**Comment by skerbis** [comment]
Dieses Release scheint es hier in GitHub nicht zu geben.

**Comment by phoebusryan** [comment]
Huch, die Version sollte noch gar nicht im Installer sein. Nehme sie wieder raus. Kannst aktuell aber die vorherige nutzen.

**Comment by ynamite** [comment]
Einfach zur Info, das Problem besteht weiterhin bei der Version im Installer.

**Comment by phoebusryan** [comment]
Stimmt. Weil ich nicht rausgefunden habe wie ich sie löschen kann. Früher ging das in my.redaxo. Heute ist da lediglich ein Hinweis 'Die Möglichkeit zur Ansicht und zum Löschen der Versionen hier an dieser Stelle wird noch kommen.'

**Comment by skerbis** [comment]
@phoebusryan das machst du im REDAXO Installer

**Comment by phoebusryan** [comment]
@skerbis hat die Version nun rausgenommen.
