### ISSUE TITLE
Google benötigt neuerdings API-Key: Wechsel zu anderem Provider?

### ISSUE THREAD

**Issue by schuer** [phoebusryan/rex_address#4]
Das Addon funktioniert nicht mehr, weil Google zwischenzeitlich seine Policy dahingehend geändert hat, dass nun für jede neue Anwendung ein API-Key benötigt wird.

Man könnte das Addon um die Möglichkeit erweitern, einen Google-API-Key zu hinterlegen, oder aber man könnte stattdessen vollständig auf einen anderen Provider wechseln. OpenStreetMap bietet sich an, und um das Handling zu vereinfachen könnte http://leafletjs.com verwendet werden.

**Comment by skerbis** [comment]
Gibt es mittlerweile ein freies Geocoding auf Basis der Adresse für OSM? Ich wüsste nicht, dass OSM einen solchen Dienst anbietet.

**Comment by phoebusryan** [comment]
Mir spielt es keine Rolle, was für ein Anbieter ich nutze bei dem Addon. Google Maps hat sich damals angeboten. Wenn es gescheite Alternativen gibt, kann ich es gerne anpassen.

**Comment by skerbis** [comment]
Ok, gefunden. Geocoding geht mit http://wiki.openstreetmap.org/wiki/Nominatim

**Comment by AWqxKAWERbXo** [comment]
Scheinbar ist niemandem aufgefallen, dass dieses Addon ohne API-Key nicht mehr funktioniert. Wird es überhaupt noch eingesetzt? Soltle man hier nicht auf Basis von YForm weiterarbeiten?

**Comment by phoebusryan** [comment]
Also ich nutze das Addon selbst nicht mehr. Fand es damals super und hilfreich. Mittlerweile setze ich aber auch auf global_settings oder eben yForm.

Aus meiner Sicht könnte man das Addon einstampfen. Wird glaube ich eh kaum genutzt. :-)

**Comment by schuer** [comment]
Aber bitte nicht löschen. Immer alles behalten und stattdessen archivieren, das geht in den Settings hier bei GitHub.

**Comment by AWqxKAWERbXo** [comment]
+1 für archivieren
