### ISSUE TITLE
Addon-Name: `rex_`-Prefix entfernen

### ISSUE THREAD

**Issue by schuer** [phoebusryan/rex_address#5]
Der Konsens bei FOR ist, keine Prefixe zu verwenden. Bei einem bereits veröffentlichten Addon ist der Wechsel allerdings mit etwas Aufwand verbunden:
1. Prüfen, ob der neue Addon-Key verfügbar ist
2. Addon mit neuem Key bei MyREDAXO anlegen
3. Repo umbenennen
4. Alte Bezeichnung im gesamten Addon auf neue wechseln
5. Neues Major-Release veröffentlichen mit Hinweis auf neuen Namen
6. Ggfls Hinweis im Forum hinterlassen, denn Nutzer des alten Addons kriegen im Installer keinen Hinweis auf Updates mehr

**Comment by schuer** [comment]
Diskussion im Slack: Die Umbenennung soll erst nach Fertigstellung der neuen Website angegangen werden. Bei der Integration wird es dann vermutlich bessere Möglichkeiten geben als jetzt.

**Comment by phoebusryan** [comment]
https://github.com/redaxo/redaxo/issues/814

**Comment by schuer** [comment]
Wie schon zuvor bei den anderen rex-Addons und im Slack besprochen: Wir nennen das Addon manuell um auf `address`.

**Comment by schuer** [comment]
Alte Version 1.2.0 mit Hinweis auf Version 2.0.0 unter neuem Namen veröffentlicht.
