### ISSUE TITLE
Bitte noch ein wenig erweitern

### ISSUE THREAD

**Issue by skerbis** [phoebusryan/rex_address#6]
Ideal wären noch: 
a) Telefonnummer (Zentrale) 
b) optional FAX ( Ja einige haben sowas noch) 
c) E-Mail

Suppercool wären noch: 
Öffnungszeiten  / Bürozeiten

**Comment by phoebusryan** [comment]
Die ersten drei kann ich auf jeden Fall machen. Wie stellst du dir das mit den Zeiten vor? Einfach eine Textarea wo man beliebiges eingeben kann?

**Comment by skerbis** [comment]
Eine allgemeine (optionale)  Textarea würde reichen, denke ich. 
Man kann ja dann mit markup oder anders evtl. Struktur in die Ausgabe reinbringen.

**Comment by phoebusryan** [comment]
Ist nun alles drin in der neusten Version. Das letzte Feld ist einfach eine Textarea mit dem Namen "Info". Damit kannst du machen was du willst.

**Comment by skerbis** [comment]
Danke
